### ISSUE TITLE
Error in package "TypeError: Cannot read property 'beginPacket' of undefined"

### ISSUE THREAD

**Issue by sabas1080** [Microsoft/pxt-common-packages#388]
Hi 

**Describe the bug**
Im trying to make a packet to manage the  LoRa radio of the MKR1300, but when i call one block i have the next error message "TypeError: Cannot read property 'beginPacket' of undefined"

**To Reproduce**
This is my code
https://github.com/ElectronicCats/pxt-common-packages/tree/lora/libs/lora

**Screenshots**
 
![captura de pantalla 2018-08-06 a la s 14 44 01](https://user-images.githubusercontent.com/2874292/43737554-4e2a7ab6-9987-11e8-998e-aca42b015be6.png)

![kapture 2018-08-06 at 14 46 12](https://user-images.githubusercontent.com/2874292/43737721-d62f4784-9987-11e8-8326-ad3d203df98d.gif)

**Desktop (please complete the following information):**
 - OS: Mac OS Sierra
 - Browser chrome
 - Version 67

**Additional context**
Add support MKR1300 pullrequest https://github.com/Microsoft/pxt-maker/pull/63

Thanks

**Comment by riknoll** [comment]
Looks like the simulator can't find your shim implementation.

Your repo setup might be the issue. How are you including the package in your project? I see that you are serving locally so did you `npm link` your local clone of `pxt-common-packages` before serving?

Just in case, here are the commands (the order is important):

```
cd pxt-common-packages
npm install
cd ../pxt-maker
npm install
npm link ../pxt-common-packages
```

If that doesn't fix your issue then can you check the output of `pxt serve` to see if there are any stack traces showing up in the build? Could be that the step to compile the simulator code in `pxt-common-packages` is failing.

**Comment by sabas1080** [comment]
output of pxt serve

```
***
*** Build failed: target build failed: ENOENT: no such file or directory, open '/Users/sabas/Documents/proyectoshd/pxt-produccion/pxt-maker/libs/lora/pxt.json'
Error: ENOENT: no such file or directory, open '/Users/sabas/Documents/proyectoshd/pxt-produccion/pxt-maker/libs/lora/pxt.json'
    at Object.fs.openSync (fs.js:579:3)
    at Object.fs.readFileSync (fs.js:485:33)
    at readJson (/Users/sabas/Documents/proyectoshd/pxt-produccion/pxt-maker/node_modules/pxt-core/built/nodeutil.js:245:26)
    at readPkgConfig (/Users/sabas/Documents/proyectoshd/pxt-produccion/pxt-maker/node_modules/pxt-core/built/nodeutil.js:251:14)
    at Object.resolveMd (/Users/sabas/Documents/proyectoshd/pxt-produccion/pxt-maker/node_modules/pxt-core/built/nodeutil.js:468:19)
    at updateTOC (/Users/sabas/Documents/proyectoshd/pxt-produccion/pxt-maker/node_modules/pxt-core/built/pxt.js:133012:30)
    at buildTargetCoreAsync (/Users/sabas/Documents/proyectoshd/pxt-produccion/pxt-maker/node_modules/pxt-core/built/pxt.js:133027:5)
    at /Users/sabas/Documents/proyectoshd/pxt-produccion/pxt-maker/node_modules/pxt-core/built/pxt.js:132602:36
    at tryCatcher (/Users/sabas/Documents/proyectoshd/pxt-produccion/pxt-maker/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/sabas/Documents/proyectoshd/pxt-produccion/pxt-maker/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/sabas/Documents/proyectoshd/pxt-produccion/pxt-maker/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/sabas/Documents/proyectoshd/pxt-produccion/pxt-maker/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/sabas/Documents/proyectoshd/pxt-produccion/pxt-maker/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/sabas/Documents/proyectoshd/pxt-produccion/pxt-maker/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/sabas/Documents/proyectoshd/pxt-produccion/pxt-maker/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/sabas/Documents/proyectoshd/pxt-produccion/pxt-maker/node_modules/bluebird/js/release/async.js:17:14)
***
```

**Comment by sabas1080** [comment]
`Pxt clean` causes the error

**Comment by sabas1080** [comment]
But with 

`npm link ../pxt-common-packages`

Thanks @riknoll
